apiVersion: batch/v1
kind: Job
metadata:
  name: titanic-model-training
  labels:
    app: titanic-training
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: titanic-training
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: mlops-training:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://host.docker.internal:5000"
            - name: MODEL_NAME
              value: "titanic-classifier"
          command: ["python", "model_training.py"]
