name: train-titanic
description: null
version: 6db4ccf891a8d93f47fa6179b5ff3493

work_queue_name: default
tags: []
parameters: {}
schedule: null
infra_overrides: {}
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command: null
  stream_output: true
  block_type_slug: process
  _block_type_slug: process

flow_name: train
manifest_path: null
storage: null
path: /training
entrypoint: model_training.py:train
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
