name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  PYTHON_VERSION: "3.11"
  MLFLOW_TRACKING_URI: "file:./mlruns"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r training/requirements.txt
          pip install -r api/requirements.txt
          pip install -r app/requirements.txt

      - name: Run tests (placeholder)
        run: |
          pytest || echo "Add tests when available"

      - name: Smoke-train model
        run: python training/model_training.py